version: '3'

services:
  generator:
    container_name: "algorand-block-generator"
    build:
      context: ./../../../
      dockerfile: ./cmd/block-generator/docker/Dockerfile-generator
    environment:
      PORT: "11111"
    ports:
      - 11111:11111
    volumes:
      # Override generator config file.
      - ../scenarios/config.mixed.jumbo.yml:/config/config.yml

  indexer:
    container_name: "indexer"
    build:
      context: ./../../../
      dockerfile: ./cmd/block-generator/docker/Dockerfile-indexer
    environment:
      PORT: 8888
      CONNECTION_STRING: "host=indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"
      ALGOD_NET: "generator:11111"
    ports:
      - 8888:8888

  indexer-db:
    image: "postgres:13-alpine"
    container_name: "indexer-postgres"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db

  prometheus:
    image: "prom/prometheus"
    container_name: "prometheus"
    ports:
      - 9090:9090
    volumes:
      # Install prometheus config
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: "grafana/grafana"
    container_name: "grafana"
    ports:
      - 3000:3000
    environment:
      GF_PATHS_CONFIG: /etc/grafana/ours.ini
    volumes:
      - ./grafana.ini:/etc/grafana/ours.ini
      - ./grafana_prometheus_datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml


