version: '3'

services:
  indexer:
    image: "indexer-test-env"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8980:8980
    restart: unless-stopped
    environment:
      DATABASE_NAME: pgdb
    depends_on: 
      - indexer-db

  indexer-db:
    image: "postgres"
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: indexer
      POSTGRES_DB: pgdb
